[package]
distribution = "2201.13.1"
org = "ballerina"
name = "pdf"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["pdf", "html", "html-to-pdf", "converter", "document"]
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerina-pdf"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "pdf-native"
version = "1.0.0"
path = "../native/build/libs/pdf-native-1.0.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "3.0.4"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox-io"
version = "3.0.4"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "3.0.4"

[[platform.java21.dependency]]
groupId = "commons-logging"
artifactId = "commons-logging"
version = "1.3.4"

[[platform.java21.dependency]]
groupId = "org.jsoup"
artifactId = "jsoup"
version = "1.18.3"

[[platform.java21.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-simple"
version = "2.0.16"
